### ISSUE TITLE
Implement a state machine for tracking changes to Lit Mag Adoption models.

### ISSUE THREAD

**Issue by phyllisstein** [phyllisstein/clmp#1]
Implement a state machine based on gocardless/statesman that will allow changes to the "state" of Lit Mag Adoption models to be tracked and presented to the user as a history of actions.

- [x] Install Rubygem.
- [ ] Determine rough list of possible states each model can be in.
- [ ] Determine sets of actions that should be automatically taken upon certain state transitions.
- [ ] Write additional code required for API to act on transition changes.
- [ ] Build the state machines' code and wire them to the models.
- [ ] Write database queries to retrieve a list of previous transitions.
